### ISSUE TITLE
raw template working?

### ISSUE THREAD

**Issue by ririgriff** [sylhare/Reveal-Jekyll#1]
Thanks for sharing this.  Tried to do the multi-slide markdown using this code but can't seem to get the raw template working.  The slides all show up on one page.  Cannot find any demos of this feature working on the repo.

**Comment by sylhare** [comment]
Yup the raw template is working,

Look in to the [index.html](https://github.com/sylhare/Reveal-Jekyll/blob/raw/index.html) and replace "presentation" with "raw" and it should display the content of the index page as a multi page presentation. (Remove the html comments as it will mess up the rendering)
